### ISSUE TITLE
Current directory structure means test and main sources must share same directory

### ISSUE THREAD

**Issue by beresfordt** [mehalter/Multiplayer-Game-of-Life#6]
The current structure means that tests and main sources must share the same directory (tests need to be in the same package as main sources so that they have access to package local scope)

eg to create a test class for GameOfLife.java

Current location of GameOfLife.java
Multiplayer-Game-of-Life/com/mehalter/life/GameOfLife.java

The test class would have to be created as
Multiplayer-Game-of-Life/com/mehalter/life/GameOfLifeTest.java

The maven directory structure is a pretty common way of structuring main and test sources without complicating things by having them sharing the same physical location. https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

under the maven structure the main class would be:

Multiplayer-Game-of-Life/src/main/java/com/mehalter/life/GameOfLife.java

and the test class would be:

Multiplayer-Game-of-Life/src/test/java/com/mehalter/life/GameOfLife.java

**Comment by mehalter** [comment]
Okay, thanks! I am new to this type of structure, but I like it and will implement it.
